version: '3.8'
services:
  client-backend:
    image: client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/postgres

  service-db:
    image: postgres
    environment:
      POSTGRES_USER: egoravdeev
      POSTGRES_PASSWORD: egoravdeev
    ports:
      - "5432:5432"

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - client-backend

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:5050"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data: